trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'vamshikrishnakalletirundevops'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'vigneshwarasacr'
        command: buildAndPush
        repository: $(imageRepository)
        Dockerfile: '$(Build.SourcesDirectory)/Shopping/Shopping.API/Dockerfile'
        buildContext: $(Build.SourcesDirectory)/Shopping
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'vigneshwarasacr'
        command: buildAndPush
        repository: shoppingclient
        Dockerfile: '$(Build.SourcesDirectory)/Shopping/Shopping.Client/Dockerfile'
        buildContext: $(Build.SourcesDirectory)/Shopping
        tags: |
          $(tag)
